# Site settings
title: There is always one more bug.
url: "http://johngrib.github.io"
baseurl: ""

#timezone: Asia/Chongqing
description: >
  One or more sentences introducing this blog.

# Your information
email: johngrib82@gmail.com
author: 이종립(John Grib)
avatar: "//www.gravatar.com/avatar/your_email_md5?d=mm&s=135"
profile: One sentence introducing yourself.
#twitter_username: twitter_username
#github_username:  github_username

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

disqus:
  id: johngrib
  shortname: johngrib
