# Site settings
title: There is always one more bug.
url: "http://johngrib.github.io"
baseurl: ""

#timezone: Asia/Chongqing
description: >
  One or more sentences introducing this blog.

# Your information
email: johngrib82@gmail.com
author: 기계인간 John Grib
avatar: "//avatars2.githubusercontent.com/u/1855714?v=3&s=460"
profile: 유물론자
twitter_username: John_Grib
github_username: johngrib

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
disqus_shortname: johngrib   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 10
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

disqus:
  id: johngrib
  shortname: johngrib
